# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-20 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_servicearea_polygon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicearea',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='longitude',
        ),
    ]
